"""dispesas 2

Revision ID: 0a20a1f5d497
Revises: 8339b2598f39
Create Date: 2026-03-17 09:00:51.510553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a20a1f5d497'
down_revision = '8339b2598f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=False),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('despesas')
    # ### end Alembic commands ###
